# Generated by Django 4.2.3 on 2023-08-11 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mvp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissionTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Generic", max_length=100, verbose_name="template title"
                    ),
                ),
                ("image_url", models.SlugField()),
                ("description", models.TextField(max_length=250)),
                ("owner_type", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "DRAFT"), ("PUBLISHED", "PUBLISHED")],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
