# Generated by Django 4.2.3 on 2023-08-11 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0003_case_message_languagemodelresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="languagemodelresponse",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
