# Generated by Django 4.2.4 on 2023-08-25 20:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fivep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('app_source', models.CharField(max_length=255)),
                ('app_user_id', models.CharField(max_length=255)),
                ('app_password', models.CharField(max_length=255)),
                ('app_user_key', models.CharField(max_length=255)),
                ('app_encryption_key', models.CharField(max_length=255)),
                ('app_vendor_login_url', models.CharField(max_length=255)),
                ('app_vendor_key', models.CharField(max_length=255)),
                ('app_response_callback_url', models.CharField(max_length=255)),
                ('request_token', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
